### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by saxenaprerit** [Dataset-Daily/DatasetDaily#3]
The code you shared for data download from nlp library is not working.

**Comment by Poseyy** [comment]
Hi, please share logs so I can help.

**Comment by saxenaprerit** [comment]
Downloading and preparing dataset civil_comments/default (download: Unknown size, generated: Unknown size, total: Unknown size) to C:\Users\Prerit\.cache\huggingface\datasets\civil_comments\default\0.9.0...
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\Anaconda3\lib\site-packages\nlp\builder.py in incomplete_dir(dirname)
    347             try:
--> 348                 yield tmp_dir
    349                 if os.path.isdir(dirname):

~\Anaconda3\lib\site-packages\nlp\builder.py in download_and_prepare(self, download_config, download_mode, ignore_verifications, save_infos, dl_manager, **download_and_prepare_kwargs)
    362                 self._download_and_prepare(
--> 363                     dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
    364                 )

~\Anaconda3\lib\site-packages\nlp\builder.py in _download_and_prepare(self, dl_manager, verify_infos, **prepare_split_kwargs)
    415                 # Prepare split will record examples associated to the split
--> 416                 self._prepare_split(split_generator, **prepare_split_kwargs)
    417             except OSError:

~\Anaconda3\lib\site-packages\nlp\builder.py in _prepare_split(self, split_generator)
    590         generator = self._generate_examples(**split_generator.gen_kwargs)
--> 591         for key, record in utils.tqdm(generator, unit=" examples", total=split_info.num_examples, leave=False):
    592             example = self.info.features.encode_example(record)

~\Anaconda3\lib\site-packages\tqdm\notebook.py in __iter__(self, *args, **kwargs)
    217         try:
--> 218             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    219                 # return super(tqdm...) will not catch exception

~\Anaconda3\lib\site-packages\tqdm\std.py in __iter__(self)
   1128         try:
-> 1129             for obj in iterable:
   1130                 yield obj

~\Anaconda3\lib\site-packages\nlp\datasets\civil_comments\b3e6758d4f763d878cefd92861b3e9c2bb416ffda27e1a8f6d66c345b69937af\civil_comments.py in _generate_examples(self, filename, toxicity_label)
    142             reader = csv.DictReader(f)
--> 143             for row in reader:
    144                 example = {}

~\Anaconda3\lib\csv.py in __next__(self)
    111             self.fieldnames
--> 112         row = next(self.reader)
    113         self.line_num = self.reader.line_num

~\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6719: character maps to <undefined>

During handling of the above exception, another exception occurred:

PermissionError                           Traceback (most recent call last)
<ipython-input-4-e8dfb2f66f13> in <module>()
      1 # Getting the dataset
----> 2 civil = nlp.load_dataset('civil_comments')

~\Anaconda3\lib\site-packages\nlp\load.py in load_dataset(path, name, version, data_dir, data_files, split, cache_dir, download_config, download_mode, ignore_verifications, save_infos, **config_kwargs)
    515         download_mode=download_mode,
    516         ignore_verifications=ignore_verifications,
--> 517         save_infos=save_infos,
    518     )
    519 

~\Anaconda3\lib\site-packages\nlp\builder.py in download_and_prepare(self, download_config, download_mode, ignore_verifications, save_infos, dl_manager, **download_and_prepare_kwargs)
    368                 self.info.size_in_bytes = self.info.dataset_size + self.info.download_size
    369                 # Save info
--> 370                 self.info.write_to_directory(self._cache_dir)
    371 
    372         # Save to datasetinfos

~\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~\Anaconda3\lib\site-packages\nlp\builder.py in incomplete_dir(dirname)
    352             finally:
    353                 if os.path.exists(tmp_dir):
--> 354                     shutil.rmtree(tmp_dir)
    355 
    356         # Create a tmp dir and rename to self._cache_dir on successful exit.

~\Anaconda3\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    492             os.close(fd)
    493     else:
--> 494         return _rmtree_unsafe(path, onerror)
    495 
    496 # Allow introspection of whether or not the hardening against symlink

~\Anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    387                 os.unlink(fullname)
    388             except OSError:
--> 389                 onerror(os.unlink, fullname, sys.exc_info())
    390     try:
    391         os.rmdir(path)

~\Anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    385         else:
    386             try:
--> 387                 os.unlink(fullname)
    388             except OSError:
    389                 onerror(os.unlink, fullname, sys.exc_info())

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Prerit\\.cache\\huggingface\\datasets\\civil_comments\\default\\0.9.0.incomplete\\civil_comments-train.arrow'

**Comment by Poseyy** [comment]
"The process cannot access the file because it is being used by another process"

The directory is open in another process ^

Usually these kinds of problems can be solved by a simple restart.
